version: "3.8"

networks:
  loki:

services:
  caddy:
    profiles: ["caddy"]
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    network_mode: host

  minio:
    profiles: ["log"]
    container_name: minio
    image: minio/minio:latest
    volumes:
      - minio_data_volume:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - loki
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server data --address ':9000' --console-address ':9001'
    shm_size: "1gb"

  createbuckets:
    profiles: ["log"]
    image: minio/mc
    volumes:
      - minio_data_volume:/data
    networks:
      - loki
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb data/loki-aws;
      /usr/bin/mc mb data/loki-stage;
      /usr/bin/mc mb data/loki-test;
      /usr/bin/mc anonymous set public data/loki-aws;
      /usr/bin/mc anonymous set public data/loki-stage;
      /usr/bin/mc anonymous set public data/loki-test;
      exit 0;
      "

  loki-test:
    profiles: ["log"]
    image: grafana/loki:2.9.0
    container_name: loki-test
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3199:3100"
    volumes:
      - "$PWD/config/loki/loki-config-test.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    networks:
      - loki

  loki-stage:
    profiles: ["log"]
    image: grafana/loki:2.9.0
    container_name: loki-stage
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3101:3100"
    volumes:
      - "$PWD/config/loki/loki-config-stage.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    networks:
      - loki

  loki-aws:
    profiles: ["log"]
    image: grafana/loki:2.9.0
    container_name: loki-aws
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3100:3100"
    volumes:
      - "$PWD/config/loki/loki-config-aws.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    networks:
      - loki

  prometheus:
    profiles: ["metric"]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    

  agent:
    profiles: ["metric", "trace"]
    image: grafana/agent:latest
    container_name: agent
    environment:
      - AGENT_MODE=flow
    ports:
      - "12345:12345"
      - "4318:4318"   # OTLP over HTTP receiver
    volumes: 
      - $PWD/config/agent/config.river:/etc/agent/config.river
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river

  grafana:
    profiles: ["log", "metric", "trace"]
    image: grafana/grafana:latest
    env_file:
      - .env
    container_name: grafana
    restart:
      unless-stopped
      #    environment:
      #      - TERM=linux
      #      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    ports:
      - "3000:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
      - "$PWD/config/grafana/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - loki

volumes:
  grafana_storage: {}
  minio_data_volume:
