version: "3.8"

networks:
  loki:

services:
  caddy:
    profiles: ['caddy']
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: always
    volumes: 
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    environment: 
      - AWS_REQ_IP: ${AWS_REQ_IP}
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    
  loki-test:
    profiles: ['log']
    image: grafana/loki:2.9.0
    container_name: loki-test
    ports:
      - "3199:3100"
    volumes:
      - '$PWD/grafana/loki-config-test.yml:/etc/loki/loki-config.yml'
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  loki-stage:
    profiles: ['log']
    image: grafana/loki:2.9.0
    container_name: loki-stage
    ports:
      - "3101:3100"
    volumes:
      - '$PWD/grafana/loki-config-stage.yml:/etc/loki/loki-config.yml'
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  loki-aws:
    profiles: ['log']
    image: grafana/loki:2.9.0
    container_name: loki-aws
    ports:
      - "3100:3100"
    volumes:
      - '$PWD/grafana/loki-config-aws.yml:/etc/loki/loki-config.yml'
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki


  grafana:
    profiles: ['log']
    image: grafana/grafana:latest
    env_file: 
      - .env
    container_name: grafana
    restart: unless-stopped
      #    environment:
      #      - TERM=linux
      #      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - '$PWD/grafana/grafana.ini:/etc/grafana/grafana.ini'
    networks:
      - loki
  

volumes:
  grafana_storage: {}
