version: "3.8"

networks:
  loki:

services:
  caddy:
    profiles: ["caddy"]
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    network_mode: host

  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - minio_data_volume:/data
    networks:
      - loki
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server data --address ':9000' --console-address ':9001'

    shm_size: "1gb"

  loki-test:
    profiles: ["loki"]
    image: grafana/loki:2.9.0
    container_name: loki-test
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3199:3100"
    volumes:
      - "$PWD/grafana/loki-config-test.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  loki-stage:
    profiles: ["loki"]
    image: grafana/loki:2.9.0
    container_name: loki-stage
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3101:3100"
    volumes:
      - "$PWD/grafana/loki-config-stage.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  loki-aws:
    profiles: ["loki"]
    image: grafana/loki:2.9.0
    container_name: loki-aws
    environment:
      - MINIO_ROOT_PASSWORD
      - MINIO_ROOT_USER
    ports:
      - "3100:3100"
    volumes:
      - "$PWD/grafana/loki-config-aws.yml:/etc/loki/loki-config.yml"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  grafana:
    profiles: ["grafana-console"]
    image: grafana/grafana:latest
    env_file:
      - .env
    container_name: grafana
    restart:
      unless-stopped
      #    environment:
      #      - TERM=linux
      #      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    ports:
      - "3000:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
      - "$PWD/grafana/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - loki

volumes:
  grafana_storage: {}
  minio_data_volume:
