apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    version: 1
    editable: false

  - name: Loki
    type: loki
    url: http://loki:80
    access: proxy
    isDefault: false
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    url: http://tempo:80
    access: proxy
    isDefault: false
    version: 1
    editable: false
