apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET
    access: proxy
    isDefault: false
    version: 1
    editable: true

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    version: 1
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "prometheus"
      streamingEnabled:
        search: true

  # TODO: 연결 테스트
  - name: CloudWatch
    type: cloudwatch
    uid: cloudwatch
    jsonData:
      authType: default
      defaultRegion: ap-northeast-2
    editable: true # TODO: 연결 테스트 후 false로 변경

  # TODO: 연결 테스트
  - name: PostgreSQL
    type: postgres
    uid: postgresql
    url: ${PG_HOST}:${PG_PORT}
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    jsonData:
      database: ${PG_DATABASE}
      sslmode: disable
    editable: true # TODO: 연결 테스트 후 false로 변경
