version: '3'

services:
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - --web.enable-remote-write-receiver
  #   ports:
  #     - 9090:9090

  agent:
    image: grafana/agent:latest
    container_name: agent
    environment:
      - AGENT_MODE=flow
      - HOSTNAME=agent
    volumes: 
      - ./config/config.river:/etc/agent/config.river
    ports:
      - 12345:12345
      - 4318:4318   # OTLP over HTTP receiver
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river

    
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.67.0
  #   container_name: otel-collector
  #   command: [ "--config=/etc/otelcol/otelcol-config.yml" ]
  #   volumes:
  #     - ./config/otelcol/otelcol-config.yml:/etc/otelcol/otelcol-config.yml
  #   ports:
  #     - "4317:4317"     # OTLP over gRPC receiver
  #     - "4318:4318"     # OTLP over HTTP receiver
  #     - "8888:8888"   # Prometheus metrics exposed by the collector
  #     - "8889:8889"   # Prometheus exporter metrics

  
    
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000


  