# 아키텍처 설명
# https://opentelemetry.io/docs/collector/architecture/

# 1. Receiver
# https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

# 2. Processor
# https://opentelemetry.io/docs/collector/configuration/#processors
processors:
  batch:
    timeout: 10s
    send_batch_size: 512

# 3. Exporter
# https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true

  otlp/trace:
    endpoint: tempo:4317
    tls:
      insecure: true

# Service
# https://opentelemetry.io/docs/collector/configuration/#service
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/trace]
