# 아키텍처 설명
# https://opentelemetry.io/docs/collector/architecture/

# 1. Receiver
# https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# 2. Processor
# https://opentelemetry.io/docs/collector/configuration/#processors
processors:
  batch:
    timeout: 10s
    send_batch_size: 512

# 3. Exporter
# https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  debug:
    verbosity: detailed

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

# 4. Service
# https://opentelemetry.io/docs/collector/configuration/#service
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

  # Collector 자체 모니터링을 위한 설정
  # https://opentelemetry.io/docs/collector/internal-telemetry
  telemetry:
    #   metrics:
    #     level: basic
    #     readers:
    #       - periodic:
    #           exporter:
    #             prometheus:
    #               host: prometheus
    #               port: 9090
    logs:
      level: DEBUG
      development: true
    #   processors:
    #     - batch:
    #         exporter:
    #           otlp:
    #             protocol: http/protobuf
    #             endpoint: http://loki:80/otlp
  #   traces:
  #     processors:
  #       - batch:
  #           exporter:
  #             otlp:
  #               protocol: http/protobuf
  #               endpoint: https://backend:4318

# 5. Extensions
# https://opentelemetry.io/docs/collector/configuration/#extensions
extensions:
  health_check:
