{
 "title": "LOG",
 "description": "스테이지 서버 로그를 보여줍니다! ",
 "tags": [
  "log",
  "stage-server"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Total Count: of Error",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(req_url) (rate({service_name=\"CLIENT-API\"} | json | level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Log with Error",
   "type": "logs",
   "description": "'error'를 포함하고 있는 모든 로그를 출력합니다. ",
   "gridPos": { "h": 5, "w": 15, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"CLIENT-API\"} |~ `(?i)error` | json | label_format status_color=\"{{if and (ge .res_statusCode `200`) (lt .res_statusCode `300`)}}94{{else if and (ge .res_statusCode `300`) (lt .res_statusCode `400`) }}93{{else}}91{{end}}\" | label_format msg_color=\"{{if (eq .msg `request completed`)}}92{{else}}91{{end}}\" | line_format \"\\u001b[{{ .status_color }}m{{alignLeft 4 .res_statusCode}}\\u001b[0m {{alignLeft 6 .req_method}} {{alignLeft 50 .req_url}} \\u001b[{{ .msg_color }}m{{.msg}}\""
    }
   ]
  },
  {
   "title": "Stage-client",
   "type": "logs",
   "description": "스테이지서버의 Backend-Client에서 오는 에러입니다! \n(Uptime Kuma에서 오는 리퀘스트는 제거했습니다.)",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{service_name=\"CLIENT-API\"} |= `info` !~ `(?i)Uptime-Kuma` | json | label_format status_color=\"{{if and (ge .res_statusCode `200`) (lt .res_statusCode `300`)}}94{{else if and (ge .res_statusCode `300`) (lt .res_statusCode `400`) }}93{{else}}91{{end}}\" | label_format msg_color=\"{{if (eq .msg `request completed`)}}92{{else}}91{{end}}\" | line_format \"\\u001b[{{ .status_color }}m{{alignLeft 4 .res_statusCode}}\\u001b[0m {{alignLeft 6 .req_method}} {{alignLeft 50 .req_url}} \\u001b[{{ .msg_color }}m{{.msg}}\""
    }
   ]
  },
  {
   "title": "Stage-admin",
   "type": "logs",
   "description": "스테이지서버의 Backend-Admin에서 오는 에러입니다! ",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "{service_name=\"ADMIN-API\"} |= `info` |  json | label_format status_color=\"{{if and (ge .res_statusCode `200`) (lt .res_statusCode `300`)}}94{{else if and (ge .res_statusCode `300`) (lt .res_statusCode `400`) }}93{{else}}91{{end}}\" | label_format msg_color=\"{{if (eq .msg `request completed`)}}92{{else}}91{{end}}\" | line_format \"\\u001b[{{ .status_color }}m{{alignLeft 4 .res_statusCode}}\\u001b[0m {{alignLeft 6 .req_method}} {{alignLeft 20 .req_body_operationName}} \\u001b[{{ .msg_color }}m{{.msg}}\""
    }
   ]
  },
  { "title": "DEBUG Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Prisma Logs - Client",
   "type": "logs",
   "description": "Prisma Debug 로그입니다! ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"CLIENT-API\"} |= `debug` | json | line_format `{{ .query}} `"
    }
   ]
  },
  {
   "title": "Prisma Logs - Admin",
   "type": "logs",
   "description": "Prisma Debug 로그입니다! ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"ADMIN-API\"} |= `debug` | json | line_format `{{ .query}} `"
    }
   ]
  }
 ]
}