{
 "title": "API Metrics",
 "tags": [
  "deploy-server",
  "metric"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "The number of EC2 instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(system_cpu_utilization{job=~\"$job\"}) by (instance))",
     "legendFormat": "APIs"
    }
   ]
  },
  {
   "title": "Total CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(25*sum(avg_over_time(process_cpu_utilization{job=~\"$job\"}[5m]))\n+25*sum(avg_over_time(system_cpu_utilization{job=~\"$job\", system_cpu_state!=\"idle\"}[5m])) )\n/count(sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"$job\"}[5m])))",
     "legendFormat": "codedang-api"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instances",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "25*sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"$job\"}[5m]))+25*sum by (instance) (avg_over_time(system_cpu_utilization{job=~\"$job\", system_cpu_state!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(25*sum(avg_over_time(process_memory_usage{job=~\"$job\"}[5m])/2147483648)\n+25*sum(avg_over_time(system_memory_utilization{job=~\"$job\", system_memory_state=\"used\"}[5m]))) \n/ count (sum by (instance) (avg_over_time(process_memory_usage{job=~\"$job\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "EC2 CPU Utilization",
   "type": "timeseries",
   "description": "AWS EC2 > Codedang-API-Instance > Monitoring",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "25*sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"backend-client-metric\"}[5m]))+25*sum by (instance) (avg_over_time(system_cpu_utilization{job=~\"backend-client-metric\", system_cpu_state!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}-cli"
    },
    {
     "expr": "25*sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"backend-admin-metric\"}[5m]))+25*sum by (instance) (avg_over_time(system_cpu_utilization{job=~\"backend-admin-metric\", system_cpu_state!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}-admin"
    },
    {
     "expr": "25*sum(avg_over_time(process_cpu_utilization[5m]))+25*sum(avg_over_time(system_cpu_utilization{system_cpu_state!=\"idle\"}[5m]))",
     "legendFormat": "total_usage"
    }
   ]
  },
  {
   "title": "Service CPU Utilization",
   "type": "timeseries",
   "description": "AWS ECS > Codedang-API > Codedang-Client-API-Service > Health",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "100*sum (avg_over_time(system_cpu_utilization{job=\"backend-client-metric\", system_cpu_state!=\"idle\"}[5m])) + 100*sum (avg_over_time(process_cpu_utilization{job=\"backend-client-metric\"}[5m]))",
     "legendFormat": "backend-client-metric"
    },
    {
     "expr": "100*sum (avg_over_time(system_cpu_utilization{job=\"backend-admin-metric\", system_cpu_state!=\"idle\"}[5m])) + 100*sum (avg_over_time(process_cpu_utilization{job=\"backend-admin-metric\"}[5m]))",
     "legendFormat": "backend-admin-metric"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Packets Dropped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "system_network_dropped_total{}",
     "legendFormat": "{{job}}: {{system_network_direction}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_network_errors_total{}",
     "legendFormat": "{{job}}: {{system_network_direction}}"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "timeseries",
   "description": "Received packet bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\", job=\"backend-client-metric\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(system_network_io_total{network_io_direction=\"receive\", job=\"backend-admin-metric\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "timeseries",
   "description": "Transmitted packet bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"transmit\", job=\"backend-client-metric\"}[1m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "increase(system_network_io_total{network_io_direction=\"transmit\", job=\"backend-admin-metric\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"transmit\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}