{
 "title": "LOG",
 "description": "AWS 서버 로그를 보여줍니다! ",
 "tags": [
  "deploy-server",
  "log"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Log with Error (TEST)",
   "type": "logs",
   "description": "시스템 운영에 치명적일 수 있는 오류만을 출력",
   "gridPos": { "h": 5, "w": 19, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\".*Api.*\"} |~ `(?i)error` != `\"level\\\":\\\"info\\\"`"
    }
   ]
  },
  {
   "title": "Client",
   "type": "logs",
   "description": "AWS 서버의 ECS_API - Client 에서 오는 로그입니다! \n(Uptime Kuma에서 오는 리퀘스트는 제거했습니다.)",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\".*Client-Api.*\"} |= `info` !~ `(?i)Uptime-Kuma` | pattern `<_>=<ec2_instance_id> log=<log>` | logfmt --strict --keep-empty log | line_format `{{.log}}`"
    }
   ]
  },
  {
   "title": "Admin",
   "type": "logs",
   "description": "AWS 서버의 ECS_API - Admin 에서 오는 로그입니다! \n(Uptime Kuma에서 오는 리퀘스트는 제거했습니다.)",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ADMIN-API\"} |= ``"
    }
   ]
  },
  {
   "title": "IRIS",
   "type": "logs",
   "description": "AWS 서버의 IRIS 에서 오는 로그입니다! ",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{container_name=~\".*Iris.*\"} |= `info` !~ `(?i)Uptime-Kuma` | pattern `<_>=<ec2_instance_id> log=<log>` | logfmt --strict --keep-empty log | line_format `{{.log}}`"
    }
   ]
  }
 ]
}