{
 "title": "Submission 상세",
 "description": "Client-API의 `/submission` API를 Log와 Trace를 기반으로 상세히 분석합니다.",
 "tags": [
  "trace",
  "log"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "ServiceName",
    "label": "서비스 이름",
    "query": {}
   },
   { "name": "TraceID", "label": "Trace ID" }
  ]
 },
 "panels": [
  { "title": "성능 지표(응답 시간)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "평균 제출 ~ 응답 시간",
   "type": "stat",
   "description": "들어온 요청이 Client-API 서버부터 MQ, Iris를 거쳐 돌아오는데 걸리는 시간 평균",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Submission Graph",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "filters": [
      {
       "id": "8b602cec",
       "operator": "=",
       "scope": "span",
       "tag": "http.method",
       "value": [ "POST" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$ServiceName" ],
       "valueType": "string"
      },
      {
       "id": "38f05353",
       "operator": "=",
       "scope": "span",
       "tag": "http.route",
       "value": [ "/api/submission" ]
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.http.method=\"POST\" && resource.service.name=~\"$ServiceName\" && span.http.route=~\"/api/submission\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "제출 현황", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "제출 개수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "제출 현황",
   "type": "timeseries",
   "description": "시간에 따른 `/api/submission` 요청 추이",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$ServiceName\"} | req_params_0 =~ `submission` | req_method = `POST` [$__auto]))"
    }
   ]
  },
  { "title": "개별 상세 분석", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "제출 현황",
   "type": "table",
   "description": "Trace 대상",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$ServiceName\"} | req_params_0 =~ `submission` | req_method = `POST`"
    }
   ]
  },
  {
   "title": "Trace 상세",
   "type": "traces",
   "description": "선택된 `Trace ID`를 상세 분석합니다.",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "filters": [
      {
       "id": "2eb37c61",
       "operator": "=",
       "scope": "span",
       "value": [],
       "valueType": "int"
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${TraceID}",
     "tableType": "traces"
    }
   ]
  }
 ]
}