name: Local Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Load dotenv from secret for Grafana Configuration
      run: |
        cat <<EOF > .env
        # Sensitive configurations from GitHub Secrets
        GF_SMTP_HOST = ${{ secrets.SMTP_HOST }}
        GF_SMTP_USER = ${{ secrets.SMTP_USER }}
        GF_SMTP_PASSWORD = ${{ secrets.SMTP_PASSWORD }}
        GF_SMTP_FROM_ADDRESS = ${{ secrets.FROM_ADDRESS }}
        EOF

    - name: Check if log containers are running
      id: check-container
      run: |
        {
          echo 'stdout<<EOF'
          docker compose --profile log ps -q
          echo EOF
        } >> "$GITHUB_OUTPUT"
    
    - name: Set up Caddy
      env:
        AWS_REQ_IP: ${{ secrets.AWS_NAT_IP }}
      run: |
        docker compose --profile caddy up -d

    - name: Initialize containers
      if: steps.check-container.outputs.stdout == ''
      run: |
        docker compose --profile log up -d --no-recreate
        
    - name: Run Docker Compose Of Log
      run: |
        docker compose --profile log up -d
    