name: Local Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Grafana Configuration
      run: |
        cat <<EOF > ./grafana/.env
        # Sensitive configurations from GitHub Secrets
        GF_SMTP_HOST = ${{ secrets.SMTP_HOST }}
        GF_SMTP_USER = ${{ secrets.SMTP_USER }}
        GF_SMTP_PASSWORD = ${{ secrets.SMTP_PASSWORD }}
        GF_SMTP_FROM_ADDRESS = ${{ secrets.FROM_ADDRESS }}
        EOF
        
    - name: Run Docker Compose
      run: |
        cd ./grafana
        docker compose up -d
